---
title: "diet.matrix"
output: html_document
---

#File to look at how much of a predator's diet is made up of mesopelagic fish from the Ecopath model in Koehn et al. (2016)

```{r}
setwd("/Users/sallydowd/Documents/GitHub/mesopelagic-fishing/Data/")
getwd()
models <- "~/DietMatrices"
file.names <- dir(models, pattern = ".csv") #Will pull files that end in .csv 

#Grab specifically the diet files 
dietfiles = grep(pattern = 'diet', file.names, value = TRUE)

#Load diet file from original Ecopath model

origdiet = read.csv(file = "/Users/sallydowd/Documents/GitHub/mesopelagic-fishing/Data/Diet_CalCur_USE.csv", header = TRUE)
meso_row = which(origdiet[,1] == "mesopelagics") 
```

#How many predators eating meospelagics
```{r}
n = length(which(origdiet[15,-1] > 0)) # 42 predators have diets > 0 on mesopelagics 
# not including column 1, which just had the row number 

#Make diet matrix to house all diets on mesopelagics 
preddiets = matrix(NA, nrow = 500, ncol = n) # 500 models, n predators 
```

#Set where ever files are stored
```{r}
setwd("/Users/sallydowd/Documents/GitHub/mesopelagic-fishing/Data/DietMatrices")
for(i in 1:500) {
  file2 <- read.csv(dietfiles[i], header = TRUE)
  file2 = as.matrix(file2)
  meso_row_pull = (file2[meso_row,-1]) # -1 to remove the column that says that row number
  vecdiet = meso_row_pull[which(meso_row_pull > 0)]
  preddiets[i,] = vecdiet
  print(i)
}
```

#Then find min and max for each column, should be min and max for each predator
```{r}
library(matrixStats)
minimum.diet <- colMins(preddiets) #ColMins will return minimum value for each column 
minimum.diet <- as.data.frame(minimum.diet)
write.csv(minimum.diet, "/Users/SallyDowd/Documents/OTZ.manuscript/Excel/minimum.diet.csv")

maximum.diet <- colMaxs(preddiets)
maximum.diet <- as.data.frame(maximum.diet)
write.csv(maximum.diet, "/Users/SallyDowd/Documents/OTZ.manuscript/Excel/maximum.diet.csv")

```


