---
title: "100 Rsim runs"
output: html_document
---

#
```{r}
library(dplyr)
library(readr)
library(Rpath)
library(data.table)
library(tidyr)
library(ggplot2)
```

#Load this each time 
```{r}
GroupInfo_CalCur_USE <- read.csv("../Data/Groupinfo_CalCur-USE.csv")  
Diet_CalCur_USE <- read.csv("../Data/Diet_CalCur_USE.csv")  

## need to add row and column names from example files
base_list <-list.files(path = "../Data/500BaseParameters/",
               pattern = "*.csv", 
               full.names = T)
diet_list <-list.files(path = "../Data/DietMatrices/",
               pattern = "*.csv", 
               full.names = T)
Cbase_list <- list()
Cdiet_list <- list()
```

#Don't need to run this again!! 
```{r}
#Add columns to base parameters
groups <- GroupInfo_CalCur_USE %>%
  select(Group, Type, Unassim, BioAcc, ProdCons, DetInput, DetritusFate, Fleet1_Discards) %>%
  mutate(X = 1:94)
groups

#Extract row 94 from Group info (Fleet 1)
Fleet1 <- GroupInfo_CalCur_USE[94, ] %>% select(Biomass, EE, PB, QB, Fleet1_Landings) %>% mutate(X= 94)

#Rename rows in diet files 
groups2 <- Diet_CalCur_USE %>% select(DIETS) %>% mutate(X= 1:94)

#Rename columns in diet file
group_vector <- groups2$DIETS[1:92]
group_vector <- as.data.frame(c("DIETS", group_vector))
group_vector <- groups2[,"DIETS"]

test <- read_csv("../Data/DietMatrices/diet100227.csv")
test_vector <- colnames(test)[1:93]

#First loop for group: rename columns, add Fleet 1 row (assigned position X=94), add new parameters (columns) onto dataset, redu column order
#for (i in 1:500) {
 Cbase_list[[i]] <- read.csv(base_list[i]) %>% 
    rename(Biomass = "V1", PB = "V2", QB = "V3", EE = "V4", Fleet1_Landings = "V5")
 Cbase_list[[i]] <- bind_rows(Fleet1, Cbase_list[[i]]) %>% arrange(X) %>% left_join(groups, by= "X") %>% select(-X) %>% relocate(Group)
col_order <- c("Group", "Biomass", "EE", "PB", "QB", "Type", "Unassim", "BioAcc", "ProdCons", "DetInput", "DetritusFate", "Fleet1_Landings", "Fleet1_Discards")
Cbase_list[[i]] <- Cbase_list[[i]][, col_order]
write.csv(Cbase_list[[i]], paste("output", base_list[i]))
}

z<- read_csv(base_list[1])

colnamesgroups<- c("DIETS", group_vector[1:93])
#Diet matrices: #REMOVE IMPORT ROW??? ROW 94 (V93) IN TEST DATA
#for (i in 1:500) {
Cdiet_list[[i]] <- read_csv(diet_list[i], col_names = colnamesgroups ) %>% select(-Detritus)
Cdiet_list[[i]]<- Cdiet_list[[i]][-1,]
Cdiet_list[[i]] <- Cdiet_list[[i]] %>%
  mutate(DIETS = c(colnamesgroups[2:94], "Import"))
write.csv(Cdiet_list[[i]], diet_list[i])
}

z2 <- read_csv(diet_list[1])

```

#Loop through 500 data sets!! 

#Reading in data, unbalanced model
```{r}
CalCur_unbal2_list <- list() #Creating an empty list to store vectors so can index 

  for (i in 1:500) {
  Cbase2 <-  base_list[[i]] 
  Cdiet2 <- diet_list[[i]]

  #Edit the datasets
  CalCur_unbal2_list[[i]] <- read.rpath.params(Cbase2, Cdiet2)
  CalCur_unbal2_list[[i]][[1]] <- CalCur_unbal2_list[[i]][[1]] %>%
    select(-X)
  CalCur_unbal2_list[[i]][[1]][93, 5] <- NA
  CalCur_unbal2_list[[i]][[1]][CalCur_unbal2_list[[i]][[1]] == -1] <- NA
   CalCur_unbal2_list[[i]][[2]] <- CalCur_unbal2_list[[i]][[2]] %>%
    select(-X)

  check.rpath.params(CalCur_unbal2_list[[i]])
  }
CalCur_unbal2_list[[439]]
```

#Calculating outliers

##Biomass 
```{r}
seven_models <- CalCur_unbal2_list[c(67, 126, 237, 343, 396, 430, 472)]
rest_of_models <- CalCur_unbal2_list[-c(67, 126, 237, 343, 396, 430, 472)]

for (i in 1:493) {
rest_of_models[[i]] <- rest_of_models[[i]]$model %>% dplyr::select(Biomass, QB, PB, EE, Group) %>% filter(Group== "mesopelagics")
}

table_Biomass <- bind_rows(rest_of_models) %>% group_by(Group) %>% summarize(IQR_biomass= IQR(Biomass), quantile_lower = quantile(Biomass, 0.25), quantile_upper = quantile(Biomass, 0.75)) %>% mutate(lower_outlier = quantile_lower - (1.5*IQR_biomass), upper_outlier= quantile_upper + (1.5*IQR_biomass)) 

table_1 <- seven_models[[1]]$model %>% dplyr::select(Biomass, QB, PB, EE, Group) %>% filter(Group == "mesopelagics") %>% group_by(Group) %>% summarize(biomass_7= mean(Biomass))

table_Biomass %>% left_join(table_1) %>% mutate(outlier= ifelse(biomass_7 < lower_outlier|biomass_7 > upper_outlier, TRUE, FALSE))

outlier <- list()
for (i in 1:7) {
seven_out <- seven_models[[i]]$model %>% dplyr::select(Biomass, QB, PB, EE, Group) %>% filter(Group== "mesopelagics")
outlier[i] <- seven_out %>% left_join(table_Biomass) %>% mutate(outlier= ifelse(Biomass < lower_outlier|Biomass > upper_outlier, TRUE, FALSE)) %>% select(outlier)
}
outlier[1]

table_Biomass_7 <- bind_rows(seven_models) %>% group_by(Group) %>% summarize(biomass_493 = mean(Biomass), sd= sd(Biomass))
```

##QB
```{r}
seven_models <- CalCur_unbal2_list[c(67, 126, 237, 343, 396, 430, 472)]
rest_of_models <- CalCur_unbal2_list[-c(67, 126, 237, 343, 396, 430, 472)]

for (i in 1:493) {
rest_of_models[[i]] <- rest_of_models[[i]]$model %>% dplyr::select(Biomass, QB, PB, EE, Group) %>% filter(Group== "mesopelagics")
}

table_QB <- bind_rows(rest_of_models) %>% group_by(Group) %>% summarize(IQR_QB= IQR(QB), quantile_lower = quantile(QB, 0.25), quantile_upper = quantile(QB, 0.75)) %>% mutate(lower_outlier = quantile_lower - (1.5*IQR_QB), upper_outlier= quantile_upper + (1.5*IQR_QB)) 

outlier <- list()
for (i in 1:7) {
seven_out <- seven_models[[i]]$model %>% dplyr::select(Biomass, QB, PB, EE, Group) %>% filter(Group== "mesopelagics")
outlier[i] <- seven_out %>% left_join(table_QB) %>% mutate(outlier= ifelse(QB < lower_outlier|QB > upper_outlier, TRUE, FALSE)) %>% select(outlier)
print(outlier[i])
}
```

##PB
```{r}
seven_models <- CalCur_unbal2_list[c(67, 126, 237, 343, 396, 430, 472)]
rest_of_models <- CalCur_unbal2_list[-c(67, 126, 237, 343, 396, 430, 472)]

for (i in 1:493) {
rest_of_models[[i]] <- rest_of_models[[i]]$model %>% dplyr::select(Biomass, QB, PB, EE, Group) %>% filter(Group== "mesopelagics")
}

table_PB <- bind_rows(rest_of_models) %>% group_by(Group) %>% summarize(IQR_PB= IQR(PB), quantile_lower = quantile(PB, 0.25), quantile_upper = quantile(PB, 0.75)) %>% mutate(lower_outlier = quantile_lower - (1.5*IQR_PB), upper_outlier= quantile_upper + (1.5*IQR_PB)) 

outlier <- list()
for (i in 1:7) {
seven_out <- seven_models[[i]]$model %>% dplyr::select(Biomass, QB, PB, EE, Group) %>% filter(Group== "mesopelagics")
outlier[i] <- seven_out %>% left_join(table_PB) %>% mutate(outlier= ifelse(PB < lower_outlier|PB > upper_outlier, TRUE, FALSE)) %>% select(outlier)
print(outlier[i])
}
```

#Creating a balanced Ecopath model 
```{r}
Cal_bal2 <- list()
for (i in 1:500) {
Cal_bal2[[i]] <- rpath(CalCur_unbal2_list[[i]]) 
  cbind(Cal_bal2[[i]]$Group, Cal_bal2[[i]]$EE)
  cbind(Cal_bal2[[i]]$Group, Cal_bal2[[i]]$TL) 
}
Cal_bal2[[430]]
```

#Creating base scenario 
```{r}
 #Define different functional groups
  all_species <- Cal_bal$Group[1:92] 
  mammals <- Cal_bal$Group[71:85] 
  seabirds <- c(Cal_bal$Group[60:70], Cal_bal$Group[86:92])
  pred_fish  <- Cal_bal$Group[33:59] 
  forage <- Cal_bal$Group[19:27]
  diet_over_0.05 <- c(Cal_bal$Group[29], Cal_bal$Group[33], Cal_bal$Group[38], Cal_bal$Group[42], Cal_bal$Group[48], Cal_bal$Group[51], Cal_bal$Group[54], Cal_bal$Group[56], Cal_bal$Group[63], Cal_bal$Group[70], Cal_bal$Group[76], Cal_bal$Group[85])
diet_over_0.05

  #Base scenario
  base_sim_scene2 <- list()
  scene0.2 <- list()
  run0.2 <- list()
  for (i in 1:500) {
  yearlist = 2001:2050

base_sim_scene2[[i]] <- rsim.scenario(Cal_bal2[[i]], CalCur_unbal2_list[[i]], years = yearlist)
scene0.2[[i]] <- base_sim_scene2[[i]]
run0.2[[i]] <- rsim.run(scene0.2[[i]], method='AB', years=yearlist) 
#rsim.plot(run0[[i]], all_species) #This isn't working
  }

rsim.plot(run0.2[[500]])

```

#End biomass
```{r}
end_biomass <- function(rsim){return(rsim$out_Biomass[dim(rsim$out_Biomass)[1], 2:(dim(rsim$out_Biomass)[2])])}
end_biomass
```

```{r}
target_sp <- "mesopelagics"
target_F <- 0.25
names(target_F) <- target_sp 

scene6.2 <- list()
run6.2 <- list()
assessment2 <- list()
catches2 <- list()
for (i in 1:500){
scene6.2[[i]] <- copy(base_sim_scene2[[i]])
run6.2[[i]] <- rsim.run(scene6.2[[i]], method = 'AB', years=2001)
for (yr in 2002:2050){
  # stock assessment based on current biomass * error
  # use this if including two species: assessment <- end_biomass(run3)[target_sp] * (runif(2) + 0.5)   
assessment2[[i]] <- end_biomass(run6.2[[i]])[target_sp] * (runif(length(target_sp)) + 0.5) #argument of length 0 means input is of length zero 
assessment2[[i]]
  # convert target F * assessment to a total catch 
  catches2[[i]] <- target_F * assessment2[[i]]
  # apply each catch to each species
  for (sp in target_sp){
    scene6.2[[i]] <- adjust.fishing(scene6.2[[i]], "ForcedCatch", sp, yr, value=catches2[[i]][sp])
  }
  # run 1 year
  run6.2[[i]] <- rsim.step(scene6.2[[i]], run6.2[[i]], method = 'AB', year.end=yr)  #Says in Rsim document on NOAA github that older versions of Ecosim use AB and new versions use 'RK4', default for Rpath is RK4 but we aren't using it??
}  
  }
rsim.plot(run6.2[[500]], all_species)
```

#Manipulating output data
```{r}
rsim.plot.fun <- function(Rsim.output, spname, indplot = F, ...){
  opar <- par(no.readonly = T)
  if(indplot == F){
    biomass <- Rsim.output$out_Biomass[, 2:ncol(Rsim.output$out_Biomass)]
    n <- ncol(biomass)
    start.bio <- biomass[1, ]
    start.bio[which(start.bio == 0)] <- 1
    rel.bio <- matrix(NA, dim(biomass)[1], dim(biomass)[2])
    for(isp in 1:n) rel.bio[, isp] <- biomass[, isp] / start.bio[isp]
  }
  rel.bio
} 

#Convert 500 rsim models into a data frame 
names_spp.2 <- run6$params$spname[2:94]
z_6.2 <- list()
data_6.2 <- list()
for (i in 1:500) {
z_6.2[[i]] <- rsim.plot.fun(run6.2[[i]])
z_6.2[[i]] <- as.data.frame(z_6.2[[i]])
names(z_6.2[[i]]) <- names_spp.2
z_6.2[[i]]$month <- 1:600
data_6.2[[i]] <- gather(z_6.2[[i]], key = spp, value = biomass, -month)
data_6.2[[i]] <- data_6.2[[i]] %>% filter(month==600) %>% mutate(X= i)
}
```

#Confidence intervals: Want 95% CI for each model at month 600 for each commercially and noncommercially valuable species
```{r}
#Combine datasets into one: remove the rsim simulations that are incorrect
entire_data_6 <- bind_rows(data_6.2) %>% filter(X == 67)
entire_data_6 <- bind_rows(data_6.2) %>% filter(!X %in% c(67, 126, 237, 343, 396, 430, 472)) %>% arrange(spp)
entire_data_6 <- transform(entire_data_6,ID=as.numeric(factor(spp))) #Add column for ID that correlates to each different species 
#Off for mesopelagics: row 67 (5.42), 126 (4.86), 237(1.1),343(8.26), 396(4.69), 430 (4.82), 472 (#2.183) 
#Off for sharks: row 67 (15.58), row 126 (17.95), row 237 (2.30), 343 (27.85),  396(17.568), 430 (9.22), 472(6.74),  
#Off for dolphins: row 67 (15.62), 126 (12.21), 237 (2.73), 343(15.75), 396(18), 430(9.11), 472(4.82),  

#Calculate CI:
n <- 500
t_star <- 1.960
sample_mean <- list()
sd_error <- list()
CI_lower <- list()
CI_upper <- list()

for (i in unique(entire_data_6$ID)){
subdf <- subset(x=entire_data_6, subset=ID==i)
sample_mean[[i]] <- mean(subdf$biomass)
sd_error[[i]] <- (sd(subdf$biomass))/(sqrt(n))
CI_lower[[i]] <- sample_mean[[i]] - (t_star*sd_error[[i]])
CI_upper[[i]] <- sample_mean[[i]] + (t_star*sd_error[[i]])
}

df2 <- as.data.frame(do.call(rbind, CI_upper)) %>% rename("CI_upper" = V1) %>% mutate(ID = 1:93)
df1 <- as.data.frame(do.call(rbind, CI_lower)) %>% rename("CI_lower"= V1) %>% mutate(ID = 1:93) %>% left_join(df2, by = "ID") %>% relocate(ID)

#Calculate quantiles
quantile_0.025 <- list()
quantile_0.975 <- list()

for (i in unique(entire_data_6$ID)){
subdf2 <- subset(x=entire_data_6, subset=ID==i)
quantile_0.025[[i]] <- quantile(subdf2$biomass, 0.025)
quantile_0.975[[i]] <- quantile(subdf2$biomass, 0.975)
}

df_quant2 <- as.data.frame(do.call(rbind, quantile_0.975)) %>% mutate(ID = 1:93)
df_quant1 <- as.data.frame(do.call(rbind, quantile_0.025)) %>% mutate(ID = 1:93) %>% left_join(df_quant2, by = "ID") %>% relocate("ID")

#Statistics
sum_data_6 <- entire_data_6 %>% group_by(spp, ID) %>% summarise(mean_biomass = mean(biomass), sd_biomass= sd(biomass), median_biomass = median(biomass)) %>% left_join(df1, by = "ID")
sum_data_6 <- sum_data_6 %>% left_join(df_quant1, by = "ID") %>% rename(quant_2.5 = "2.5%", quant_97.5 = "97.5%")
sum_data_6 <- sum_data_6 %>% mutate("median.value" = cut(median_biomass, 
                      breaks = c(-Inf, 1, Inf),
                      labels = c("Decreasing", "Increasing"),
                      right = TRUE), "difference"= quant_97.5-quant_2.5)

write.csv(sum_data_6, "/Users/sallydowd/Documents/OTZ.manuscript/Excel/sum_data_6.csv")

max(sum_data_6$difference)*100
min(sum_data_6$difference)*100
mean(sum_data_6$difference)*100

#Check to see if 500 end biomass values for each species are normally distributed
#Only one is normally distributed-mesopelagics 
listids <- list()
for (ids in unique(entire_data_6$ID)){
    subdf <- subset(x=entire_data_6, subset=ID==ids) #Subset returns subsets of data frame that meet certain condition (keeps original dataset intact and creates another dataframe with specific ID) 
    listids[[ids]] <- shapiro.test(subdf$biomass) #Doing analysis on subsetting dataframes
    print(listids[[ids]])
}
```

#Graph
```{r}
#Organize datasets

#Species overlap between noncomm and commercially valuable 
noncommerical_predators
new_noncomm <- noncommerical_predators[- c(9,7,11,4,6,17,1,12,8,10,19,5,16,18,15,14,13,3)]
#Highlight albacore (9), arrowtooth (7), canary rockfish (11),greenstriped (4), lingcod (6), longspine thorny (17), other cephal (1), pacific ocean perch (12), sablefish (8), salmon (10), sharks (19), shelf rock (5), shortspine thorny (16), skates (18), slope rockfish (15), splitnose rockfish (14), widow rock (13), and yellowtail rock (3) in commercially valuable and remove from noncommercially valuable 

#Filter datasets
comm_value <- sum_data_6 %>% filter(spp %in% commercial_predators) 
write.csv(comm_value, "/Users/sallydowd/Documents/OTZ.manuscript/Excel/comm_value.csv")
noncomm_value <- sum_data_6 %>% filter(spp %in% new_noncomm)
write.csv(noncomm_value, "/Users/sallydowd/Documents/OTZ.manuscript/Excel/noncomm_value.csv")

#Make plots
comm_value_500 <- comm_value %>% ggplot(aes(fill = median.value)) + 
  geom_pointrange(aes(y=spp, x=median_biomass, xmin=quant_2.5, xmax= quant_97.5), size=0.5, shape=22) + 
  scale_fill_grey() + 
scale_y_discrete(limits = unique(rev(comm_value$spp)), labels= c("Greenstriped" = expression(bold("Greenstriped rock.")), "P. Ocean Perch"= expression(bold("P. ocean perch")), "Albacore" = expression(bold("Albacore")), "Arrowtooth" = expression(bold("Arrowtooth flounder")), "Canary rock."= expression(bold("Canary rock.")), "Lingcod"= expression(bold("Lingcod")), "Longspine thorny."= expression(bold("Longspine thorny.")), "Other cephal."= expression(bold("Other cephal.")), "Sablefish"= expression(bold("Sablefish")), "Salmon"= expression(bold("Salmon")), "Sharks"= expression(bold("Sharks")), "Shelf rock."= expression(bold("Shelf rock.")), "Shortspine thorny."= expression(bold("Shortspine thorny.")), "Skates"= expression(bold("Skates")), "Slope rock."= expression(bold("Slope rock.")), "Splitnose rock."= expression(bold("Splitnose rock.")), "Widow rock."= expression(bold("Widow rock.")), "Yellowtail rock."= expression(bold("Yellowtail rock.")))) +
theme(legend.title= element_text(size = 12), legend.text = element_text(size= 10), axis.text=element_text(size=10, family= "Helvetica
serif"), axis.title=element_text(size=12)) + 
geom_vline(xintercept = 1, size = 0.5) + 
xlab("Relative biomass") + ylab("Species") + labs(fill = "Median biomass", title= "A") + 
theme_bw() + theme(panel.border = element_blank()) +
theme(axis.line = element_line(colour = "black")) +
theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
ggsave(width = 6, height = 4, "~/Documents/OTZ.Manuscript/Images/500.commercial.25.jpeg")
comm_value_500

    #Next steps: rename some species (no capitalization)
noncomm_value_500 <- noncomm_value %>% ggplot(aes(fill = median.value)) + geom_pointrange(aes(y=spp, x=median_biomass, xmin=quant_2.5, xmax= quant_97.5), size=0.5, color="black", shape=22) + 
scale_fill_grey() + 
scale_y_discrete(limits = unique(rev(noncomm_value$spp)), labels= c("Western Gull" = "Western gull", "Tufted Puffin" = "Tufted puffin", "Sea Lions"= "Sea lions", "Resident Orcas"= "Resident orcas", "Leach's S. Petrel" ="Leach's s. petrel", "Juv. Ele. Seal"="Juv. elephant seal", "Double corm."= "Double cormorant", "Brandt's corm." = "Brandt's cormorant", "Juv. rock." = "Juv. rock.")) + 
geom_vline(xintercept = 1, size = 0.5) + 
xlab("Relative biomass") + ylab("Species") + labs(fill = "Median biomass", title= "B") + 
theme_bw() + theme(panel.border = element_blank()) +
theme(axis.line = element_line(colour = "black")) +
theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
theme(legend.title= element_text(size = 12), legend.text = element_text(size= 10), axis.text=element_text(size=10), axis.title=element_text(size=12)) + 
ggsave(width = 6, height = 4, "~/Documents/OTZ.Manuscript/Images/500.noncommercial.25.jpeg")
noncomm_value_500
```







 
  

